name: ci

on:
  # Run action on certain pull request events
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

  # After pushing to main
  push:
    branches: [main]

  # Nightly job on default (main) branch
  schedule:
    - cron: '0 0 * * *'

  # Allow tests to be run manually
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.11
        with:
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
      - name: Run formatting
        run: pixi run lint
      - name: Build the environment
        run: pixi run build
  doc_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install pytest pytest-md pytest-emoji sybil docker
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
      - name: Run pytest
        uses: pavelzw/pytest-action@v2
        with:
          verbose: true
          emoji: true
          job-summary: true
          custom-arguments: '-vvs test/'
